# 3章 データ構造

## 3.4 pandas

### 3.4.1　DataFrameの機能

In [1]:
import pandas as pd

In [2]:
usa_data = pd.Series(
    [13.33, 14.02, 14.02, 14.25], index=["2000", "2001", "2002", "2003"]
)

In [3]:
usa_data

2000    13.33
2001    14.02
2002    14.02
2003    14.25
dtype: float64

In [4]:
india_data = pd.Series([9.02, 9.01, 8.84, 8.84], index=["2000", "2001", "2002", "2003"])

In [5]:
df = pd.DataFrame({"USA": usa_data, "India": india_data})

In [6]:
df

        USA  India
2000  13.33   9.02
2001  14.02   9.01
2002  14.02   8.84
2003  14.25   8.84

### DataFrameのパフォーマンス

##### メモ `pip install openpyxl`が必要

In [11]:
df = pd.read_excel("../data/SG_GEN_PARL.xlsx")
df = df.drop(
    [
        "Goal",
        "Target",
        "Indicator",
        "SeriesCode",
        "SeriesDescription",
        "GeoAreaCode",
        "Reporting Type",
        "Sex",
        "Units",
    ],
    axis=1,
)
df = df.set_index("GeoAreaName").transpose()

In [12]:
df

GeoAreaName,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
2000,NaN,5.16,3.16,7.14,15.45,5.26,28.02,3.05,22.45,26.78,...,22.18,13.33,12.12,6.80,0.00,12.14,26.00,0.66,10.13,14.00
2001,NaN,5.16,3.42,7.14,15.45,5.26,26.46,3.05,22.97,26.78,...,22.18,14.02,12.12,7.20,0.00,9.70,26.00,0.66,10.13,9.33
2002,NaN,5.71,3.42,14.29,15.45,5.26,30.74,3.05,25.33,26.78,...,22.26,14.02,12.12,7.20,0.00,9.70,26.00,0.67,12.03,10.00
2003,NaN,5.71,6.17,14.29,15.45,5.26,30.74,3.05,25.33,33.88,...,22.26,14.25,12.12,7.20,1.92,9.70,27.31,0.67,12.03,10.00
2004,NaN,5.71,6.17,14.29,15.45,5.26,30.74,4.58,25.33,33.88,...,21.36,14.25,12.12,7.20,1.92,9.70,27.31,0.33,12.03,10.00
2005,NaN,6.43,6.17,14.29,15.00,10.53,33.73,5.34,24.67,33.88,...,21.36,14.94,12.12,17.50,3.85,9.70,27.31,0.33,12.03,10.00
2006,27.31,7.14,6.17,28.57,15.00,10.53,36.19,5.34,24.67,33.88,...,30.41,15.17,11.11,17.50,3.85,17.37,27.31,0.33,12.66,16.00
2007,27.31,7.14,6.17,28.57,15.00,10.53,35.02,5.34,24.67,32.24,...,30.41,16.32,11.11,17.50,3.85,17.96,27.31,0.33,14.65,16.67
2008,27.69,7.14,7.71,25.00,15.00,10.53,40.00,9.16,26.67,32.79,...,30.41,16.78,12.12,17.50,3.85,18.56,25.76,0.33,15.19,16.00
2009,27.69,7.14,7.71,25.00,37.27,10.53,40.00,8.40,26.67,27.32,...,30.41,17.01,12.12,17.50,3.85,18.56,25.76,0.33,15.19,15.24
2010,27.31,16.43,7.71,35.71,38.64,10.53,38.52,9.16,27.33,27.87,...,30.65,16.78,14.14,22.00,3.85,17.47,25.76,0.33,14.01,14.95
2011,27.71,16.43,7.71,35.71,38.64,10.53,38.52,9.16,24.67,27.87,...,36.00,16.78,15.15,22.00,3.85,16.97,25.76,0.33,14.01,14.95
2012,27.71,15.71,7.97,50.00,38.18,10.53,37.35,8.40,24.67,27.87,...,36.00,16.82,12.12,22.00,1.92,16.97,24.40,0.33,11.47,14.95
2013,27.71,15.71,31.60,50.00,34.09,10.53,37.35,10.69,24.67,27.87,...,36.00,17.78,12.12,22.00,0.00,16.97,24.40,0.33,11.47,14.95
2014,27.71,20.00,31.60,50.00,36.82,10.53,36.58,10.69,26.00,32.24,...,36.00,18.29,13.13,22.00,0.00,16.97,24.30,0.33,10.76,31.48
2015,27.71,20.71,31.60,50.00,36.82,11.11,36.19,10.69,26.67,30.60,...,36.00,19.35,13.13,16.00,0.00,16.97,24.30,0.33,12.66,31.48
2016,27.71,20.71,31.60,39.29,36.82,11.11,35.80,10.69,26.67,30.60,...,36.56,19.35,16.16,16.00,0.00,14.37,24.30,0.00,12.66,31.48
2017,27.71,22.86,31.60,32.14,38.18,11.11,38.91,9.92,28.67,30.60,...,36.39,19.08,20.20,16.00,0.00,22.16,26.72,0.00,17.96,32.59
2018,27.71,27.86,25.76,32.14,30.45,11.11,38.91,18.10,28.67,34.43,...,37.18,19.49,20.20,16.00,0.00,22.16,26.72,0.00,17.96,33.20
2019,NaN,29.29,25.76,32.14,30.00,11.11,38.82,24.24,30.00,37.16,...,36.90,23.56,22.22,16.00,0.00,22.16,26.72,0.33,17.96,31.85
2020,27.02,29.51,25.76,46.43,30.00,11.11,40.86,23.48,30.46,39.34,...,36.90,23.43,21.21,32.00,0.00,22.16,26.72,0.33,16.77,31.85
2021,27.02,29.51,25.97,46.43,29.55,11.11,42.41,22.73,31.13,39.89,...,36.72,27.25,24.24,32.65,0.00,22.16,26.72,0.33,16.77,31.85
2022,27.02,35.71,8.11,46.43,29.55,11.11,44.75,34.58,31.13,41.53,...,36.86,27.71,25.25,33.33,0.00,NaN,30.26,0.00,15.06,30.57
2023,NaN,35.71,7.86,46.43,33.64,11.11,44.75,35.51,38.41,40.44,...,37.40,29.43,26.26,33.57,1.92,NaN,30.26,0.00,14.97,30.57

In [13]:
%%timeit
df["India_fraction"] = df["India"] / 100

26.5 μs ± 77.4 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [14]:
%%timeit
df["India_fraction"] = df["India"].apply(lambda x: x / 100)

28.8 μs ± 194 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [15]:
%%timeit
df["India_fraction"] = [row["India"] / 100 for index, row in df.iterrows()]

235 μs ± 4.37 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)